version: "3.3"

services:
  db:
    image: postgres
    volumes:
        - ./database/schema:/docker-entrypoint-initdb.d
    ports:
      - "6543:5432"
    env_file:
      - ".env"
  
  rest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    env_file:
      - ".env"
    depends_on:
      - db
